/*
 * EazyShop Products APIs Definition
 *
 * # About Us **EazyShop** is a open market product selling company. Any website can list our products by  using our _APIs_. Shipping & other logistics will be taken care by us. You will get an `Affiliate commision` for selling our products. # Categories suported   - Mobiles     - Apple     - Samsung     - OnePlus   - Laptops   - Televisions   - Headphones 
 *
 * API version: 0.0.1
 * Contact: support@eazyshop.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Address struct {

	AddressLine string `json:"addressLine"`

	City string `json:"city"`

	State string `json:"state"`

	Zipcode string `json:"zipcode"`

	IsOfficeAddress bool `json:"isOfficeAddress,omitempty"`
}
