/*
 * EazyShop Products APIs Definition
 *
 * # About Us **EazyShop** is a open market product selling company. Any website can list our products by  using our _APIs_. Shipping & other logistics will be taken care by us. You will get an `Affiliate commision` for selling our products. # Categories suported   - Mobiles     - Apple     - Samsung     - OnePlus   - Laptops   - Televisions   - Headphones 
 *
 * API version: 0.0.1
 * Contact: support@eazyshop.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1/",
		Index,
	},

	Route{
		"CategoriesCategoryIdGet",
		strings.ToUpper("Get"),
		"/v1/categories/{categoryId}",
		CategoriesCategoryIdGet,
	},

	Route{
		"CategoriesGet",
		strings.ToUpper("Get"),
		"/v1/categories",
		CategoriesGet,
	},

	Route{
		"OrdersDelete",
		strings.ToUpper("Delete"),
		"/v1/orders",
		OrdersDelete,
	},

	Route{
		"OrdersGet",
		strings.ToUpper("Get"),
		"/v1/orders",
		OrdersGet,
	},

	Route{
		"OrdersPost",
		strings.ToUpper("Post"),
		"/v1/orders",
		OrdersPost,
	},

	Route{
		"OrdersPut",
		strings.ToUpper("Put"),
		"/v1/orders",
		OrdersPut,
	},

	Route{
		"ProductsGet",
		strings.ToUpper("Get"),
		"/v1/products",
		ProductsGet,
	},

	Route{
		"ProductsProductIdGet",
		strings.ToUpper("Get"),
		"/v1/products/{productId}",
		ProductsProductIdGet,
	},
}
