# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class InlineResponse201(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: int=None):  # noqa: E501
        """InlineResponse201 - a model defined in Swagger

        :param order_id: The order_id of this InlineResponse201.  # noqa: E501
        :type order_id: int
        """
        self.swagger_types = {
            'order_id': int
        }

        self.attribute_map = {
            'order_id': 'orderId'
        }
        self._order_id = order_id

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse201':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_201 of this InlineResponse201.  # noqa: E501
        :rtype: InlineResponse201
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> int:
        """Gets the order_id of this InlineResponse201.


        :return: The order_id of this InlineResponse201.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this InlineResponse201.


        :param order_id: The order_id of this InlineResponse201.
        :type order_id: int
        """

        self._order_id = order_id
