# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.address import Address  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class InlineResponse200(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, order_id: int=None, products: List[Product]=None, address: Address=None):  # noqa: E501
        """InlineResponse200 - a model defined in Swagger

        :param order_id: The order_id of this InlineResponse200.  # noqa: E501
        :type order_id: int
        :param products: The products of this InlineResponse200.  # noqa: E501
        :type products: List[Product]
        :param address: The address of this InlineResponse200.  # noqa: E501
        :type address: Address
        """
        self.swagger_types = {
            'order_id': int,
            'products': List[Product],
            'address': Address
        }

        self.attribute_map = {
            'order_id': 'orderId',
            'products': 'products',
            'address': 'address'
        }
        self._order_id = order_id
        self._products = products
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'InlineResponse200':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The inline_response_200 of this InlineResponse200.  # noqa: E501
        :rtype: InlineResponse200
        """
        return util.deserialize_model(dikt, cls)

    @property
    def order_id(self) -> int:
        """Gets the order_id of this InlineResponse200.


        :return: The order_id of this InlineResponse200.
        :rtype: int
        """
        return self._order_id

    @order_id.setter
    def order_id(self, order_id: int):
        """Sets the order_id of this InlineResponse200.


        :param order_id: The order_id of this InlineResponse200.
        :type order_id: int
        """

        self._order_id = order_id

    @property
    def products(self) -> List[Product]:
        """Gets the products of this InlineResponse200.


        :return: The products of this InlineResponse200.
        :rtype: List[Product]
        """
        return self._products

    @products.setter
    def products(self, products: List[Product]):
        """Sets the products of this InlineResponse200.


        :param products: The products of this InlineResponse200.
        :type products: List[Product]
        """

        self._products = products

    @property
    def address(self) -> Address:
        """Gets the address of this InlineResponse200.


        :return: The address of this InlineResponse200.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address: Address):
        """Sets the address of this InlineResponse200.


        :param address: The address of this InlineResponse200.
        :type address: Address
        """

        self._address = address
