# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.address import Address  # noqa: F401,E501
from swagger_server.models.product import Product  # noqa: F401,E501
from swagger_server import util


class OrdersBody1(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, products: List[Product]=None, address: Address=None):  # noqa: E501
        """OrdersBody1 - a model defined in Swagger

        :param products: The products of this OrdersBody1.  # noqa: E501
        :type products: List[Product]
        :param address: The address of this OrdersBody1.  # noqa: E501
        :type address: Address
        """
        self.swagger_types = {
            'products': List[Product],
            'address': Address
        }

        self.attribute_map = {
            'products': 'products',
            'address': 'address'
        }
        self._products = products
        self._address = address

    @classmethod
    def from_dict(cls, dikt) -> 'OrdersBody1':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The orders_body_1 of this OrdersBody1.  # noqa: E501
        :rtype: OrdersBody1
        """
        return util.deserialize_model(dikt, cls)

    @property
    def products(self) -> List[Product]:
        """Gets the products of this OrdersBody1.


        :return: The products of this OrdersBody1.
        :rtype: List[Product]
        """
        return self._products

    @products.setter
    def products(self, products: List[Product]):
        """Sets the products of this OrdersBody1.


        :param products: The products of this OrdersBody1.
        :type products: List[Product]
        """

        self._products = products

    @property
    def address(self) -> Address:
        """Gets the address of this OrdersBody1.


        :return: The address of this OrdersBody1.
        :rtype: Address
        """
        return self._address

    @address.setter
    def address(self, address: Address):
        """Sets the address of this OrdersBody1.


        :param address: The address of this OrdersBody1.
        :type address: Address
        """

        self._address = address
